[default]
# Database
database_url = "postgresql://postgres:postgres@postgres:5432/transcription_db"
postgres_user = "postgres"
postgres_password = "postgres"
postgres_db = "transcription_db"

# Redis
redis_url = "redis://redis:6379/0"
redis_host = "redis"
redis_port = 6379

# NATS
nats_url = "nats://nats:4222"
nats_jetstream_enabled = true

# Telegram
bot_token = "your_bot_token_here"
webhook_url = ""

# AI Models
whisper_model_size = "large-v3"
pyannote_token = "your_huggingface_token_here"
model_cache_dir = "./models"

# Monitoring
prometheus_port = 9090
log_level = "INFO"

# Security
secret_key = "your_secret_key_here"
access_token_expire_minutes = 10080  # 7 days

# Application
debug = true
environment = "development"
project_name = "Audio Transcription Bot"
api_host = "0.0.0.0"
api_port = 8000

# Limits
max_file_size_mb = 200
max_concurrent_tasks = 5

# Features
enable_diarization = true
enable_webapp = true
auto_delete_files = true
auto_delete_timeout_hours = 24

# File Storage
storage_type = "nats"
storage_path = "./storage"

# Grafana
grafana_user = "admin"
grafana_password = "admin"