global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
    metrics_path: '/metrics'

  - job_name: 'api'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'

  - job_name: 'bot'
    static_configs:
      - targets: ['app:9000']
    metrics_path: '/metrics'

  - job_name: 'transcription'
    static_configs:
      - targets: ['app:9001']
    metrics_path: '/metrics'

  - job_name: 'diarization'
    static_configs:
      - targets: ['app:9002']
    metrics_path: '/metrics'